version: "3.9"
services:
  db:
    image: postgres:15
    container_name: fastify_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: user_profiles
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fastify_net

  app:
    build: .
    container_name: fastify_app
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/user_profiles
    depends_on:
      - db
    networks:
      - fastify_net

volumes:
  db_data:

networks:
  fastify_net:
    driver: bridge
